### ISSUE TITLE
Xcode 10.2 compile error

### ISSUE THREAD

**Issue by ahamel** [DeclarativeHub/Bond#609]
UITableView.swift line 398

Argument type 'TableViewBondBinder<B>' does not conform to expected type 'TableViewBond'

**Comment by srdanrasic** [comment]
Have you updated to v7.3.2?

**Comment by ahamel** [comment]
Upgrading to 7.3 was a breaking change with lots of rework due to API changes. I'm on the 6.x version. Using Bond (6.10.2)

**Comment by jonathanfoster** [comment]
@ahamel Looks like you can resolve the issue by adding the TableViewBond protocol to TableViewBondBinder. https://github.com/jonathanfoster/Bond/commit/f1242e65ea3c8c5bae7716cfbc9ab1e7cf9c4d17

**Comment by srdanrasic** [comment]
I'll try to make a fix release for v6.x.

**Comment by srdanrasic** [comment]
The fix is released as 6.10.3. Thanks @jonathanfoster for helping out!

**Comment by marek-hajducak** [comment]
Still Have problem with compile On Xcode 10.2

![Uploading Screen Shot 2019-03-28 at 20.10.53.png…](errors)

**Comment by srdanrasic** [comment]
It seems like you are not using version 7.3.2 or 7.3.3 @marek-hajducak .

**Comment by marek-hajducak** [comment]
Thanks so much, this solve it 👍

**Comment by ahamel** [comment]
I ended up using the fix in 6.10.3. Thanks guys!
