### ISSUE TITLE
Crash on AtomicObserver in ReactiveKit

### ISSUE THREAD

**Issue by madiguzel** [DeclarativeHub/Bond#665]
Hi,

After updating pods, my app gets crashing randomly on AtomicObserver.dispose() in ReactiveKit. I think this problem was resolved in version 3.15.3 of ReactiveKit but when I update the pod for Bond, CocoaPods downloads the version 3.15.2 of ReactiveKit. How can I force CocoaPods to download latest version of ReactiveKit? I've tried putting both Bond and ReactiveKit in Podfile without success.

And here is the crash log:

```
Simultaneous accesses to 0x283da9e10, but modification requires exclusive access.
Previous access (a modification) started at ReactiveKit AtomicObserver.dispose() + 152 (0x10d0943bc).
Current access (a read) started at:
0    libswiftCore.dylib                 0x00000001965bbbe0 swift_beginAccess + 560
1    ReactiveKit                        0x000000010d093a58 AtomicObserver.on(_:) + 288
2    ReactiveKit                        0x000000010d0946b8 protocol witness for ObserverProtocol.on(_:) in conformance AtomicObserver<A, B> + 20
3    ReactiveKit                        0x000000010d094964 ObserverProtocol.receive(completion:) + 612
4    ReactiveKit                        0x000000010d0cd6cc closure #2 in closure #1 in SignalProtocol.prefix<A>(untilOutputFrom:) + 748
5    ReactiveKit                        0x000000010d093a58 AtomicObserver.on(_:) + 484
6    ReactiveKit                        0x000000010d0946b8 protocol witness for ObserverProtocol.on(_:) in conformance AtomicObserver<A, B> + 20
7    ReactiveKit                        0x000000010d094964 ObserverProtocol.receive(completion:) + 612
8    ReactiveKit                        0x000000010d0cd4c4 closure #1 in closure #1 in SignalProtocol.prefix<A>(untilOutputFrom:) + 328
9    ReactiveKit                        0x000000010d093a58 AtomicObserver.on(_:) + 484
10   ReactiveKit                        0x000000010d0946b8 protocol witness for ObserverProtocol.on(_:) in conformance AtomicObserver<A, B> + 20
11   ReactiveKit                        0x000000010d0959b8 partial apply + 132
12   ReactiveKit                        0x000000010d093524 thunk for @escaping @callee_guaranteed (@in_guaranteed Signal<A, B>.Event) -> () + 20
13   ReactiveKit                        0x000000010d0ef668 thunk for @escaping @callee_guaranteed (@in_guaranteed Signal<A, B>.Event) -> (@out ()) + 36
14   ReactiveKit                        0x000000010d0ee89c Subject.on(_:) + 2524
15   ReactiveKit                        0x000000010d0f2278 ReplayOneSubject.on(_:) + 1048
16   ReactiveKit                        0x000000010d0f03c0 protocol witness for ObserverProtocol.on(_:) in conformance Subject<A, B> + 28
17   ReactiveKit                        0x000000010d0ed37c SubjectProtocol.send(completion:) + 636
18   ReactiveKit                        0x000000010d07cd70 DisposeBag.deinit + 252
19   ReactiveKit                        0x000000010d07cf68 DisposeBag.__deallocating_deinit + 60
20   libswiftCore.dylib                 0x00000001965bd4f0 <redacted> + 28
21   libobjc.A.dylib                    0x0000000188e0b2ac <redacted> + 352
22   libobjc.A.dylib                    0x0000000188e07d24 objc_destructInstance + 100
23   libobjc.A.dylib                    0x0000000188e0ed80 _objc_rootDealloc + 48
24   UIKitCore                          0x000000018d162d60 <redacted> + 152
25   UIKitCore                          0x000000018d59d278 <redacted> + 872
26   UIKitCore                          0x000000018cb6dfd4 <redacted> + 68
27   UIKitCore                          0x000000018cb5fc3c <redacted> + 96
```

**Comment by srdanrasic** [comment]
Hi @madiguzel, I just released 3.15.3 to CocoaPods. Hope it fixes the problem.

**Comment by madiguzel** [comment]
Hi Srdan,

Thank you for your quick reply. I've just updated pods and got the new version of ReactiveKit (3.15.4). But the same crash still exists. And additionally, main thread checker complains about UI API calls from background thread and freezes the UI in debug mode for a while.

Here is the crash log:

<img width="913" alt="Screen Shot 2019-12-11 at 14 01 07" src="https://user-images.githubusercontent.com/1685245/70616591-dc12b980-1c1f-11ea-8916-42f6306b1ae6.png">

```
Simultaneous accesses to 0x2807bbc10, but modification requires exclusive access.
Previous access (a modification) started at ReactiveKit`AtomicObserver.dispose() + 284 (0x10d3f844c).
Current access (a read) started at:
0    libswiftCore.dylib                 0x00000001965bbbe0 swift_beginAccess + 560
1    ReactiveKit                        0x000000010d3f7558 AtomicObserver.on(_:) + 448
2    ReactiveKit                        0x000000010d3f88d8 protocol witness for ObserverProtocol.on(_:) in conformance AtomicObserver<A, B> + 20
3    ReactiveKit                        0x000000010d3f8b84 ObserverProtocol.receive(completion:) + 612
4    ReactiveKit                        0x000000010d431854 closure #2 in closure #1 in SignalProtocol.prefix<A>(untilOutputFrom:) + 748
5    ReactiveKit                        0x000000010d3f7558 AtomicObserver.on(_:) + 644
6    ReactiveKit                        0x000000010d3f88d8 protocol witness for ObserverProtocol.on(_:) in conformance AtomicObserver<A, B> + 20
7    ReactiveKit                        0x000000010d3f8b84 ObserverProtocol.receive(completion:) + 612
8    ReactiveKit                        0x000000010d43164c closure #1 in closure #1 in SignalProtocol.prefix<A>(untilOutputFrom:) + 328
9    ReactiveKit                        0x000000010d3f7558 AtomicObserver.on(_:) + 644
10   ReactiveKit                        0x000000010d3f88d8 protocol witness for ObserverProtocol.on(_:) in conformance AtomicObserver<A, B> + 20
11   ReactiveKit                        0x000000010d3f9bd8 partial apply + 132
12   ReactiveKit                        0x000000010d3f6f1c thunk for @escaping @callee_guaranteed (@in_guaranteed Signal<A, B>.Event) -> () + 20
13   ReactiveKit                        0x000000010d45374c thunk for @escaping @callee_guaranteed (@in_guaranteed Signal<A, B>.Event) -> (@out ()) + 36
14   ReactiveKit                        0x000000010d452a3c Subject.on(_:) + 2472
15   ReactiveKit                        0x000000010d4566f4 ReplayOneSubject.on(_:) + 1036
16   ReactiveKit                        0x000000010d454414 protocol witness for ObserverProtocol.on(_:) in conformance Subject<A, B> + 28
17   ReactiveKit                        0x000000010d451504 SubjectProtocol.send(completion:) + 636
18   ReactiveKit                        0x000000010d3e0690 DisposeBag.deinit + 252
19   ReactiveKit                        0x000000010d3e0888 DisposeBag.__deallocating_deinit + 60
20   libswiftCore.dylib                 0x00000001965bd4f0 <redacted> + 28
21   libobjc.A.dylib                    0x0000000188e0b2ac <redacted> + 352
22   libobjc.A.dylib                    0x0000000188e07d24 objc_destructInstance + 100
23   libobjc.A.dylib                    0x0000000188e0ed80 _objc_rootDealloc + 48
24   UIKitCore                          0x000000018d162d60 <redacted> + 152
25   UIKitCore                          0x000000018d59d278 <redacted> + 872
26   UIKitCore                          0x000000018cb6dfd4 <redacted> + 68
27   UIKitCore                          0x000000018cb5fc3c <redacted> + 96
28   fastPay                            0x0000000104dfc258 outlined destroy of FormButton? + 24
29   libobjc.A.dylib                    0x0000000188df5078 <redacted> + 112
30   libobjc.A.dylib                    0x0000000188e07d24 objc_destructInstance + 88
31   libobjc.A.dylib                    0x0000000188e0ed80 _objc_rootDealloc + 48
32   UIKitCore                          0x000000018d162d60 <redacted> + 152
33   UIKitCore                          0x000000018d59d278 <redacted> + 872
```

Main thread checker issues:

```
UIControl.swift - Line 74
(UIControl.removeTarget(_:action:for:) must be used from main thread only
```

```
UIGestureRecognizer.swift - Line 128
UIView.removeGestureRecognizer(_:) must be used from main thread only
```

```
ProtocolProxyPropertyController.swift - Line 67 and 70
UITableView.delegate must be used from main thread only
```

**Comment by srdanrasic** [comment]
Alright, looks like we'll have to dig a bit deeper to get this resolved. May I suggest you revert to the version you've been using before the update until then?

**Comment by madiguzel** [comment]
I rolled back to the version which I thought it was working. But it crashes, too. Some other pods have been updated in parallel. I think they caused that problem. I'll investigate and return back to you.

**Comment by ibrahimkteish** [comment]
@srdanrasic My app is crashing a lot since I updated to `Bond 7.6.1, with ReactiveKit 3.15.4`, I believe the issue is in AtomicObserver line 70 `private let disposablesQueue = DispatchQueue(label: "com.reactive_kit.atomic_observer.disposables", qos: .userInitiated)` where the disposition of all bond's `BNDControlTarget` is not happening now on main thread check the below image:
<img width="1082" alt="Screenshot 2019-12-12 at 11 19 22" src="https://user-images.githubusercontent.com/2681868/70704460-526ff400-1cd2-11ea-964c-ec89845d38ce.png">

**Comment by madiguzel** [comment]
> I rolled back to the version which I thought it was working. But it crashes, too. Some other pods have been updated in parallel. I think they caused that problem. I'll investigate and return back to you.

@srdanrasic. I checked it again and found that the versions of frameworks below don't causes a crash.

  - Bond (7.6.1):
    - Differ (~> 1.4)
    - ReactiveKit (~> 3.14)

**Comment by srdanrasic** [comment]
I just release 7.6.2 that should fix disposing on the non-main threads. @ibrahimkteish @madiguzel

**Comment by ibrahimkteish** [comment]
@srdanrasic we just opened a [Pull Request](https://github.com/DeclarativeHub/Bond/pull/667) for that.

**Comment by LoKiLyn** [comment]
Still reproduces with 7.6.6  : <
Crash at the same place as @madiguzel

**Comment by srdanrasic** [comment]
This should no longer happen with latest ReactiveKit version.

**Comment by tonyarnold** [comment]
Sorry to resurrect this issue, but I'm seeing this stack trace in a macOS app using Bond 7.6.6 and ReactiveKit 3.16.2 - is it something I'm doing, or something that needs to be resolved upstream in RK?

**Comment by svendr** [comment]
Also discovered this bug in the 7.6.6 version. Surprisingly it only appears in Debug- and not in Release-Builds!

**Comment by tonyarnold** [comment]
@svendr have you worked out what is triggering this? I haven't gone too deep on this one, but it's stopped me in my tracks. I'll have a chance to look at what's happening next week.

**Comment by tonyarnold** [comment]
Actually, I've definitely fixed mine, and the problem was a legitimate access violation (fixed by declaring a captured closure parameter as `unowned`). Ignore me :+1:

**Comment by svendr** [comment]
@tonyarnold 

> @svendr have you worked out what is triggering this? I haven't gone too deep on this one, but it's stopped me in my tracks. I'll have a chance to look at what's happening next week.

Nope haven't spent more on this topic yet, as it only affects Debug-Builds. Your fix regarding the access violation sounds like a good hint, I'll check if we're having a similar issue
